import type { Order, Product, Client, Vendedor } from "./types"

// Vendedores
export const vendedores: Vendedor[] = [
  {
    id: "v1",
    name: "Carlos Fernández",
    email: "carlos@masoil.com.ar",
    whatsapp: "+54 11 5234-8901",
    zonas: ["Norte", "GBA"],
    isActive: true,
    role: "vendedor",
  },
  {
    id: "v2",
    name: "María González",
    email: "maria@masoil.com.ar",
    whatsapp: "+54 11 5234-8902",
    zonas: ["Capital", "Sur"],
    isActive: true,
    role: "vendedor",
  },
  {
    id: "v3",
    name: "Jorge Ramírez",
    email: "jorge@masoil.com.ar",
    whatsapp: "+54 11 5234-8903",
    zonas: ["Oeste"],
    isActive: true,
    role: "vendedor",
  },
  {
    id: "v4",
    name: "Laura Sánchez",
    email: "laura@masoil.com.ar",
    whatsapp: "+54 11 5234-8904",
    zonas: ["Norte", "Capital"],
    isActive: true,
    role: "vendedor",
  },
  {
    id: "v5",
    name: "Roberto Díaz",
    email: "roberto@masoil.com.ar",
    whatsapp: "+54 11 5234-8905",
    zonas: ["Sur", "GBA"],
    isActive: true,
    role: "vendedor",
  },
  {
    id: "admin1",
    name: "Admin Masoil",
    email: "admin@masoil.com.ar",
    whatsapp: "+54 11 5234-8900",
    zonas: ["Norte", "Capital", "Sur", "Oeste", "GBA"],
    isActive: true,
    role: "admin",
  },
]

// Products
export const products: Product[] = [
  // Limpiadores
  {
    id: "p1",
    code: "LMP-220",
    name: "Limpia Contactos 220ml",
    category: "Limpiadores",
    stock: 47,
    price: 2850,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p2",
    code: "LMP-440",
    name: "Limpia Contactos 440ml",
    category: "Limpiadores",
    stock: 8,
    price: 4200,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p3",
    code: "LMP-500",
    name: "Desengrasante Industrial 500ml",
    category: "Limpiadores",
    stock: 125,
    price: 3650,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p4",
    code: "LMP-750",
    name: "Limpia Frenos 750ml",
    category: "Limpiadores",
    stock: 0,
    price: 4890,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p5",
    code: "LMP-350",
    name: "Limpiador Multiuso 350ml",
    category: "Limpiadores",
    stock: 89,
    price: 2990,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },

  // Lubricantes
  {
    id: "p6",
    code: "LUB-220",
    name: "WD-40 220ml",
    category: "Lubricantes",
    stock: 156,
    price: 5250,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p7",
    code: "LUB-440",
    name: "Aceite Lubricante Multiuso 440ml",
    category: "Lubricantes",
    stock: 23,
    price: 3850,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p8",
    code: "LUB-SIL",
    name: "Silicona Lubricante 360ml",
    category: "Lubricantes",
    stock: 67,
    price: 4120,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p9",
    code: "LUB-GRAF",
    name: "Grasa Grafitada 400g",
    category: "Lubricantes",
    stock: 34,
    price: 6890,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p10",
    code: "LUB-LIT",
    name: "Grasa de Litio 500g",
    category: "Lubricantes",
    stock: 5,
    price: 7250,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },

  // Selladores
  {
    id: "p11",
    code: "SEL-280",
    name: "Sellador de Juntas 280ml",
    category: "Selladores",
    stock: 78,
    price: 5890,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p12",
    code: "SEL-SIL",
    name: "Silicona Selladora 300ml",
    category: "Selladores",
    stock: 91,
    price: 4650,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p13",
    code: "SEL-TERM",
    name: "Sellador Térmico 85g",
    category: "Selladores",
    stock: 43,
    price: 3280,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p14",
    code: "SEL-POL",
    name: "Sellador Poliuretano 310ml",
    category: "Selladores",
    stock: 12,
    price: 8950,
    isCustomizable: true,
    customLeadTime: 15,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },

  // Belleza
  {
    id: "p15",
    code: "BLZ-500",
    name: "Cera Líquida Premium 500ml",
    category: "Belleza",
    stock: 145,
    price: 8750,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p16",
    code: "BLZ-PAL",
    name: "Polish Abrillantador 350ml",
    category: "Belleza",
    stock: 98,
    price: 6890,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p17",
    code: "BLZ-REN",
    name: "Renovador de Plásticos 250ml",
    category: "Belleza",
    stock: 56,
    price: 5650,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p18",
    code: "BLZ-CER",
    name: "Cera Carnauba 200g",
    category: "Belleza",
    stock: 0,
    price: 12890,
    isCustomizable: true,
    customLeadTime: 15,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p19",
    code: "BLZ-VID",
    name: "Limpiavidrios Concentrado 500ml",
    category: "Belleza",
    stock: 187,
    price: 3890,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },

  // Higiene
  {
    id: "p20",
    code: "HIG-AMB",
    name: "Ambientador Citrus 360ml",
    category: "Higiene",
    stock: 234,
    price: 2650,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p21",
    code: "HIG-LAV",
    name: "Ambientador Lavanda 360ml",
    category: "Higiene",
    stock: 156,
    price: 2650,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p22",
    code: "HIG-DES",
    name: "Desinfectante Multiuso 500ml",
    category: "Higiene",
    stock: 89,
    price: 3450,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p23",
    code: "HIG-TAP",
    name: "Limpiador de Tapizados 400ml",
    category: "Higiene",
    stock: 45,
    price: 5890,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p24",
    code: "HIG-ANT",
    name: "Antibacterial en Spray 250ml",
    category: "Higiene",
    stock: 7,
    price: 4250,
    isCustomizable: false,
    customLeadTime: 0,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
  {
    id: "p25",
    code: "HIG-CUST",
    name: "Ambientador Personalizado 360ml",
    category: "Higiene",
    stock: 0,
    price: 4890,
    isCustomizable: true,
    customLeadTime: 15,
    lowStockThreshold: 25,
    criticalStockThreshold: 10,
  },
]

// Clients
export const clients: Client[] = [
  // Norte
  {
    id: "c1",
    businessName: "Taller Mecánico Norte",
    contactName: "Javier Pérez",
    whatsapp: "+54 11 4567-8901",
    email: "contacto@tallernorte.com.ar",
    zona: "Norte",
    vendedorId: "v1",
    address: "Av. San Martín 1234, Vicente López",
    paymentTerms: "30 días",
    creditLimit: 150000,
    notes: "Cliente VIP - Pedidos frecuentes",
    lastOrderDate: new Date("2025-01-12"),
    totalOrders: 87,
  },
  {
    id: "c2",
    businessName: "AutoService Express",
    contactName: "Ricardo Molina",
    whatsapp: "+54 11 4567-8902",
    email: "info@autoserviceexpress.com",
    zona: "Norte",
    vendedorId: "v1",
    address: "Calle 45 N° 567, San Isidro",
    paymentTerms: "15 días",
    creditLimit: 80000,
    notes: "",
    lastOrderDate: new Date("2025-01-10"),
    totalOrders: 34,
  },
  {
    id: "c3",
    businessName: "Lubricentro El Rápido",
    contactName: "Martín Suárez",
    whatsapp: "+54 11 4567-8903",
    email: "ventas@lubricentrorapido.com",
    zona: "Norte",
    vendedorId: "v4",
    address: "Ruta 9 Km 23, Pilar",
    paymentTerms: "30 días",
    creditLimit: 120000,
    notes: "Prefiere entregas los martes",
    lastOrderDate: new Date("2025-01-08"),
    totalOrders: 56,
  },

  // Capital
  {
    id: "c4",
    businessName: "Repuestos Capital",
    contactName: "Andrea Torres",
    whatsapp: "+54 11 4567-8904",
    email: "compras@repuestoscapital.com",
    zona: "Capital",
    vendedorId: "v2",
    address: "Av. Corrientes 2345, CABA",
    paymentTerms: "45 días",
    creditLimit: 200000,
    notes: "Cliente mayorista",
    lastOrderDate: new Date("2025-01-13"),
    totalOrders: 124,
  },
  {
    id: "c5",
    businessName: "Gomería San Telmo",
    contactName: "Pablo Rodríguez",
    whatsapp: "+54 11 4567-8905",
    email: "info@gomeriasantelmo.com",
    zona: "Capital",
    vendedorId: "v2",
    address: "Defensa 890, CABA",
    paymentTerms: "15 días",
    creditLimit: 50000,
    notes: "",
    lastOrderDate: new Date("2025-01-11"),
    totalOrders: 23,
  },
  {
    id: "c6",
    businessName: "Taller Mecánico Balvanera",
    contactName: "Diego Martínez",
    whatsapp: "+54 11 4567-8906",
    email: "diego@tallerbalvanera.com",
    zona: "Capital",
    vendedorId: "v4",
    address: "Av. Rivadavia 3456, CABA",
    paymentTerms: "30 días",
    creditLimit: 90000,
    notes: "Requiere factura A",
    lastOrderDate: new Date("2025-01-09"),
    totalOrders: 45,
  },

  // Sur
  {
    id: "c7",
    businessName: "Auto Repuestos del Sur",
    contactName: "Gustavo Fernández",
    whatsapp: "+54 11 4567-8907",
    email: "ventas@repuestossur.com",
    zona: "Sur",
    vendedorId: "v2",
    address: "Av. Hipólito Yrigoyen 789, Avellaneda",
    paymentTerms: "30 días",
    creditLimit: 110000,
    notes: "",
    lastOrderDate: new Date("2025-01-12"),
    totalOrders: 67,
  },
  {
    id: "c8",
    businessName: "Lubricentro Quilmes",
    contactName: "Fernando López",
    whatsapp: "+54 11 4567-8908",
    email: "contacto@lubricentroquilmes.com",
    zona: "Sur",
    vendedorId: "v5",
    address: "Calle Rivadavia 1234, Quilmes",
    paymentTerms: "15 días",
    creditLimit: 70000,
    notes: "Pedidos solo por la mañana",
    lastOrderDate: new Date("2025-01-07"),
    totalOrders: 38,
  },
  {
    id: "c9",
    businessName: "Taller Mecánico Lanús",
    contactName: "Cristian Gómez",
    whatsapp: "+54 11 4567-8909",
    email: "info@tallerlanus.com",
    zona: "Sur",
    vendedorId: "v5",
    address: "9 de Julio 456, Lanús",
    paymentTerms: "30 días",
    creditLimit: 85000,
    notes: "",
    lastOrderDate: new Date("2025-01-14"),
    totalOrders: 52,
  },

  // Oeste
  {
    id: "c10",
    businessName: "Taller Industrial Morón",
    contactName: "Alejandro Ruiz",
    whatsapp: "+54 11 4567-8910",
    email: "compras@tallermoron.com",
    zona: "Oeste",
    vendedorId: "v3",
    address: "Av. Gaona 2345, Morón",
    paymentTerms: "45 días",
    creditLimit: 180000,
    notes: "Cliente industrial - grandes volúmenes",
    lastOrderDate: new Date("2025-01-13"),
    totalOrders: 98,
  },
  {
    id: "c11",
    businessName: "Service Automotor Oeste",
    contactName: "Marcelo Silva",
    whatsapp: "+54 11 4567-8911",
    email: "ventas@serviceoeste.com",
    zona: "Oeste",
    vendedorId: "v3",
    address: "Buen Viaje 678, Ituzaingó",
    paymentTerms: "30 días",
    creditLimit: 95000,
    notes: "",
    lastOrderDate: new Date("2025-01-10"),
    totalOrders: 41,
  },
  {
    id: "c12",
    businessName: "Repuestos Ramos Mejía",
    contactName: "Sebastián Castro",
    whatsapp: "+54 11 4567-8912",
    email: "info@repuestosramos.com",
    zona: "Oeste",
    vendedorId: "v3",
    address: "Av. de Mayo 890, Ramos Mejía",
    paymentTerms: "15 días",
    creditLimit: 60000,
    notes: "Prefiere pagos en efectivo",
    lastOrderDate: new Date("2025-01-08"),
    totalOrders: 29,
  },

  // GBA
  {
    id: "c13",
    businessName: "Lubricentro La Matanza",
    contactName: "Héctor Vargas",
    whatsapp: "+54 11 4567-8913",
    email: "contacto@lubrilamatanza.com",
    zona: "GBA",
    vendedorId: "v1",
    address: "Av. Cristiania 3456, La Matanza",
    paymentTerms: "30 días",
    creditLimit: 100000,
    notes: "",
    lastOrderDate: new Date("2025-01-11"),
    totalOrders: 63,
  },
  {
    id: "c14",
    businessName: "Taller Mecánico Tigre",
    contactName: "Leonardo Benítez",
    whatsapp: "+54 11 4567-8914",
    email: "info@tallertigre.com",
    zona: "GBA",
    vendedorId: "v1",
    address: "Ruta 27 Km 5, Tigre",
    paymentTerms: "45 días",
    creditLimit: 140000,
    notes: "Cliente desde 2010",
    lastOrderDate: new Date("2025-01-13"),
    totalOrders: 156,
  },
  {
    id: "c15",
    businessName: "Service Automotor Merlo",
    contactName: "Daniel Ortiz",
    whatsapp: "+54 11 4567-8915",
    email: "ventas@servicemerlo.com",
    zona: "GBA",
    vendedorId: "v5",
    address: "Calle Real 567, Merlo",
    paymentTerms: "30 días",
    creditLimit: 75000,
    notes: "",
    lastOrderDate: new Date("2025-01-09"),
    totalOrders: 47,
  },
]

// Generate orders
export const orders: Order[] = [
  // Recent orders - today (Jan 14, 2025)
  {
    id: "ORD-001",
    clientId: "c1",
    clientName: "Taller Mecánico Norte",
    vendedorId: "v1",
    vendedorName: "Carlos Fernández",
    zona: "Norte",
    status: "EN_ARMADO",
    products: [
      { productId: "p1", productCode: "LMP-220", productName: "Limpia Contactos 220ml", quantity: 12, price: 2850 },
      { productId: "p6", productCode: "LUB-220", productName: "WD-40 220ml", quantity: 8, price: 5250 },
      { productId: "p15", productCode: "BLZ-500", productName: "Cera Líquida Premium 500ml", quantity: 5, price: 8750 },
    ],
    total: 120550,
    notes: "Entrega urgente solicitada",
    isCustom: false,
    estimatedDelivery: new Date("2025-01-16"),
    createdAt: new Date("2025-01-14T09:30:00"),
    updatedAt: new Date("2025-01-14T11:15:00"),
    statusHistory: [
      { status: "RECIBIDO", timestamp: new Date("2025-01-14T09:30:00"), userId: "v1", userName: "Carlos Fernández" },
      { status: "CONFIRMADO", timestamp: new Date("2025-01-14T10:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "EN_ARMADO", timestamp: new Date("2025-01-14T11:15:00"), userId: "admin1", userName: "Admin Masoil" },
    ],
    isUrgent: true,
  },
  {
    id: "ORD-002",
    clientId: "c4",
    clientName: "Repuestos Capital",
    vendedorId: "v2",
    vendedorName: "María González",
    zona: "Capital",
    status: "CONFIRMADO",
    products: [
      {
        productId: "p3",
        productCode: "LMP-500",
        productName: "Desengrasante Industrial 500ml",
        quantity: 20,
        price: 3650,
      },
      { productId: "p11", productCode: "SEL-280", productName: "Sellador de Juntas 280ml", quantity: 15, price: 5890 },
      { productId: "p20", productCode: "HIG-AMB", productName: "Ambientador Citrus 360ml", quantity: 30, price: 2650 },
    ],
    total: 240850,
    notes: "Cliente mayorista",
    isCustom: false,
    estimatedDelivery: new Date("2025-01-17"),
    createdAt: new Date("2025-01-14T08:15:00"),
    updatedAt: new Date("2025-01-14T09:00:00"),
    statusHistory: [
      { status: "RECIBIDO", timestamp: new Date("2025-01-14T08:15:00"), userId: "v2", userName: "María González" },
      { status: "CONFIRMADO", timestamp: new Date("2025-01-14T09:00:00"), userId: "admin1", userName: "Admin Masoil" },
    ],
    isUrgent: false,
  },
  {
    id: "ORD-003",
    clientId: "c10",
    clientName: "Taller Industrial Morón",
    vendedorId: "v3",
    vendedorName: "Jorge Ramírez",
    zona: "Oeste",
    status: "EN_FABRICACION",
    products: [
      {
        productId: "p14",
        productCode: "SEL-POL",
        productName: "Sellador Poliuretano 310ml",
        quantity: 50,
        price: 8950,
      },
      { productId: "p18", productCode: "BLZ-CER", productName: "Cera Carnauba 200g", quantity: 25, price: 12890 },
    ],
    total: 769750,
    notes: "Pedido customizado - Logo empresa en envases",
    isCustom: true,
    estimatedDelivery: new Date("2025-01-21"),
    createdAt: new Date("2025-01-07T10:00:00"),
    updatedAt: new Date("2025-01-14T14:30:00"),
    statusHistory: [
      { status: "RECIBIDO", timestamp: new Date("2025-01-07T10:00:00"), userId: "v3", userName: "Jorge Ramírez" },
      { status: "CONFIRMADO", timestamp: new Date("2025-01-07T11:30:00"), userId: "admin1", userName: "Admin Masoil" },
      {
        status: "EN_FABRICACION",
        timestamp: new Date("2025-01-08T09:00:00"),
        userId: "admin1",
        userName: "Admin Masoil",
        notes: "Confirmado con proveedor",
      },
    ],
    isUrgent: false,
  },
  {
    id: "ORD-004",
    clientId: "c9",
    clientName: "Taller Mecánico Lanús",
    vendedorId: "v5",
    vendedorName: "Roberto Díaz",
    zona: "Sur",
    status: "LISTO",
    products: [
      { productId: "p6", productCode: "LUB-220", productName: "WD-40 220ml", quantity: 10, price: 5250 },
      { productId: "p8", productCode: "LUB-SIL", productName: "Silicona Lubricante 360ml", quantity: 8, price: 4120 },
    ],
    total: 85460,
    notes: "",
    isCustom: false,
    estimatedDelivery: new Date("2025-01-15"),
    createdAt: new Date("2025-01-13T15:30:00"),
    updatedAt: new Date("2025-01-14T10:00:00"),
    statusHistory: [
      { status: "RECIBIDO", timestamp: new Date("2025-01-13T15:30:00"), userId: "v5", userName: "Roberto Díaz" },
      { status: "CONFIRMADO", timestamp: new Date("2025-01-13T16:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "EN_ARMADO", timestamp: new Date("2025-01-14T08:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "LISTO", timestamp: new Date("2025-01-14T10:00:00"), userId: "admin1", userName: "Admin Masoil" },
    ],
    isUrgent: false,
  },
  {
    id: "ORD-005",
    clientId: "c14",
    clientName: "Taller Mecánico Tigre",
    vendedorId: "v1",
    vendedorName: "Carlos Fernández",
    zona: "GBA",
    status: "EN_ENTREGA",
    products: [
      { productId: "p1", productCode: "LMP-220", productName: "Limpia Contactos 220ml", quantity: 15, price: 2850 },
      {
        productId: "p3",
        productCode: "LMP-500",
        productName: "Desengrasante Industrial 500ml",
        quantity: 10,
        price: 3650,
      },
      {
        productId: "p15",
        productCode: "BLZ-500",
        productName: "Cera Líquida Premium 500ml",
        quantity: 12,
        price: 8750,
      },
    ],
    total: 190250,
    notes: "Cliente VIP",
    isCustom: false,
    estimatedDelivery: new Date("2025-01-14"),
    createdAt: new Date("2025-01-13T09:00:00"),
    updatedAt: new Date("2025-01-14T07:30:00"),
    statusHistory: [
      { status: "RECIBIDO", timestamp: new Date("2025-01-13T09:00:00"), userId: "v1", userName: "Carlos Fernández" },
      { status: "CONFIRMADO", timestamp: new Date("2025-01-13T10:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "EN_ARMADO", timestamp: new Date("2025-01-13T14:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "LISTO", timestamp: new Date("2025-01-13T17:00:00"), userId: "admin1", userName: "Admin Masoil" },
      {
        status: "EN_ENTREGA",
        timestamp: new Date("2025-01-14T07:30:00"),
        userId: "admin1",
        userName: "Admin Masoil",
        notes: "Chofer: Juan Pérez",
      },
    ],
    isUrgent: true,
  },
  {
    id: "ORD-006",
    clientId: "c7",
    clientName: "Auto Repuestos del Sur",
    vendedorId: "v2",
    vendedorName: "María González",
    zona: "Sur",
    status: "ENTREGADO",
    products: [
      { productId: "p20", productCode: "HIG-AMB", productName: "Ambientador Citrus 360ml", quantity: 24, price: 2650 },
      { productId: "p21", productCode: "HIG-LAV", productName: "Ambientador Lavanda 360ml", quantity: 24, price: 2650 },
      {
        productId: "p22",
        productCode: "HIG-DES",
        productName: "Desinfectante Multiuso 500ml",
        quantity: 12,
        price: 3450,
      },
    ],
    total: 168600,
    notes: "",
    isCustom: false,
    estimatedDelivery: new Date("2025-01-13"),
    createdAt: new Date("2025-01-12T11:00:00"),
    updatedAt: new Date("2025-01-13T15:00:00"),
    statusHistory: [
      { status: "RECIBIDO", timestamp: new Date("2025-01-12T11:00:00"), userId: "v2", userName: "María González" },
      { status: "CONFIRMADO", timestamp: new Date("2025-01-12T12:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "EN_ARMADO", timestamp: new Date("2025-01-13T08:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "LISTO", timestamp: new Date("2025-01-13T10:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "EN_ENTREGA", timestamp: new Date("2025-01-13T11:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "ENTREGADO", timestamp: new Date("2025-01-13T15:00:00"), userId: "v2", userName: "María González" },
    ],
    isUrgent: false,
  },
  {
    id: "ORD-007",
    clientId: "c1",
    clientName: "Taller Mecánico Norte",
    vendedorId: "v1",
    vendedorName: "Carlos Fernández",
    zona: "Norte",
    status: "ENTREGADO",
    products: [
      { productId: "p6", productCode: "LUB-220", productName: "WD-40 220ml", quantity: 6, price: 5250 },
      { productId: "p9", productCode: "LUB-GRAF", productName: "Grasa Grafitada 400g", quantity: 4, price: 6890 },
    ],
    total: 59060,
    notes: "",
    isCustom: false,
    estimatedDelivery: new Date("2025-01-12"),
    createdAt: new Date("2025-01-11T14:00:00"),
    updatedAt: new Date("2025-01-12T16:00:00"),
    statusHistory: [
      { status: "RECIBIDO", timestamp: new Date("2025-01-11T14:00:00"), userId: "v1", userName: "Carlos Fernández" },
      { status: "CONFIRMADO", timestamp: new Date("2025-01-11T15:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "EN_ARMADO", timestamp: new Date("2025-01-12T09:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "LISTO", timestamp: new Date("2025-01-12T11:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "EN_ENTREGA", timestamp: new Date("2025-01-12T13:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "ENTREGADO", timestamp: new Date("2025-01-12T16:00:00"), userId: "v1", userName: "Carlos Fernández" },
    ],
    isUrgent: false,
  },
  {
    id: "ORD-008",
    clientId: "c2",
    clientName: "AutoService Express",
    vendedorId: "v1",
    vendedorName: "Carlos Fernández",
    zona: "Norte",
    status: "SIN_STOCK",
    products: [
      { productId: "p2", productCode: "LMP-440", productName: "Limpia Contactos 440ml", quantity: 15, price: 4200 },
      { productId: "p4", productCode: "LMP-750", productName: "Limpia Frenos 750ml", quantity: 10, price: 4890 },
    ],
    total: 111900,
    notes: "Esperando reposición de stock",
    isCustom: false,
    estimatedDelivery: new Date("2025-01-18"),
    createdAt: new Date("2025-01-11T10:00:00"),
    updatedAt: new Date("2025-01-11T12:00:00"),
    statusHistory: [
      { status: "RECIBIDO", timestamp: new Date("2025-01-11T10:00:00"), userId: "v1", userName: "Carlos Fernández" },
      {
        status: "SIN_STOCK",
        timestamp: new Date("2025-01-11T12:00:00"),
        userId: "admin1",
        userName: "Admin Masoil",
        notes: "Productos agotados",
      },
    ],
    isUrgent: false,
  },
  {
    id: "ORD-009",
    clientId: "c11",
    clientName: "Service Automotor Oeste",
    vendedorId: "v3",
    vendedorName: "Jorge Ramírez",
    zona: "Oeste",
    status: "ENTREGADO",
    products: [
      { productId: "p11", productCode: "SEL-280", productName: "Sellador de Juntas 280ml", quantity: 8, price: 5890 },
      { productId: "p12", productCode: "SEL-SIL", productName: "Silicona Selladora 300ml", quantity: 10, price: 4650 },
    ],
    total: 93620,
    notes: "",
    isCustom: false,
    estimatedDelivery: new Date("2025-01-11"),
    createdAt: new Date("2025-01-10T09:30:00"),
    updatedAt: new Date("2025-01-11T14:00:00"),
    statusHistory: [
      { status: "RECIBIDO", timestamp: new Date("2025-01-10T09:30:00"), userId: "v3", userName: "Jorge Ramírez" },
      { status: "CONFIRMADO", timestamp: new Date("2025-01-10T10:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "EN_ARMADO", timestamp: new Date("2025-01-10T14:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "LISTO", timestamp: new Date("2025-01-10T16:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "EN_ENTREGA", timestamp: new Date("2025-01-11T09:00:00"), userId: "admin1", userName: "Admin Masoil" },
      { status: "ENTREGADO", timestamp: new Date("2025-01-11T14:00:00"), userId: "v3", userName: "Jorge Ramírez" },
    ],
    isUrgent: false,
  },
  {
    id: "ORD-010",
    clientId: "c5",
    clientName: "Gomería San Telmo",
    vendedorId: "v2",
    vendedorName: "María González",
    zona: "Capital",
    status: "CANCELADO",
    products: [
      {
        productId: "p17",
        productCode: "BLZ-REN",
        productName: "Renovador de Plásticos 250ml",
        quantity: 5,
        price: 5650,
      },
    ],
    total: 28250,
    notes: "Cliente canceló por cambio en presupuesto",
    isCustom: false,
    estimatedDelivery: new Date("2025-01-12"),
    createdAt: new Date("2025-01-10T13:00:00"),
    updatedAt: new Date("2025-01-10T15:00:00"),
    statusHistory: [
      { status: "RECIBIDO", timestamp: new Date("2025-01-10T13:00:00"), userId: "v2", userName: "María González" },
      {
        status: "CANCELADO",
        timestamp: new Date("2025-01-10T15:00:00"),
        userId: "v2",
        userName: "María González",
        notes: "Solicitado por cliente",
      },
    ],
    isUrgent: false,
  },
]
